name: "Clima"
description: "A new Flutter project."
publish_to: "none" 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.1
  http: ^1.2.2
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  provider: ^6.1.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/background_image/
    - assets/fonts/
    - assets/splash_screen_image/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: assets/fonts/SpartanMB-Black.otf
      weight: 900
